### ISSUE TITLE
How to show both  tittle and  value in treemap?

### ISSUE THREAD

**Issue by arunreghu** [kurkle/chartjs-chart-treemap#12] opened 2020-07-08 05:51 UTC
tree: [{value: 100, title: 'Alpha'}, {value: 20, title: 'Beta'}, {value: 5, title: 'Gamma'}],
Your current implementation its only show title.
I want to show both title and value in treemap how to do that? Also if the title has a long text it will not fit it UI so how to wrap that text?

**Comment by kurkle** [comment] 2020-07-13 20:52
Duplicate of #7

**Closed by kurkle** 2020-07-13 20:52 UTC
Labels: duplicate
